channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::pyarrow
  - conda-forge::pip
  - bioconda::java-jdk=8
  - conda-forge::ipywidgets
  - conda-forge::nodejs
  - pip
  - pip:
    - py4j
    - bokeh
    - ipykernel
    - hail
    - pyspark==2.4.5
    - plotly
    - jupyter_server_proxy
    - jupyter-spark
    - jupyter_contrib_nbextensions
    - jupyterlab-sparkmonitor
    - grpcio
    - protobuf
