name: pipeline-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6.9
  - conda-forge::pyarrow
  - conda-forge::pandas
  - conda-forge::rpy2
  - conda-forge::pip
  - bioconda::java-jdk=8
  - conda-forge::dask
  - pip
  - pip:
    - matplotlib
    - seaborn
    - cython
    - numpy
    - plotly
    - cufflinks
    - scikit-learn
    - statsmodels
    - pandas
    - jupyter
    - jupyterlab
    - ipywidgets
    - py4j
    - keras
    - tensorflow
    - bokeh
    - ipykernel
    - hail
    - pyspark==2.4.5
    - plotly
